// Auto-generated comprehensive list of 1485 granular categories
export const ALL_GRANULAR_CATEGORIES = [
  "17 Seater Tempo Travellers On Rent\r",
  "24 Hours Bus On Rent\r",
  "24 Hours Cranes On Rent\r",
  "24 Hours Service\r",
  "24 Hours Towing Services\r",
  "24 Hours Transporters\r",
  "3 Seater Recliner Chair Wholesalers\r",
  "3D Architectural Visualization Services\r",
  "3D Printing Services\r",
  "7 Seater Car Rental\r",
  "AC Bus On Rent\r",
  "AC Dealers\r",
  "AC Dealers-Carrier\r",
  "AC Dealers-Daikin\r",
  "AC Dealers-Gree\r",
  "AC Dealers-Haier\r",
  "AC Dealers-Lloyd\r",
  "AC Dealers-Voltas\r",
  "AC On Rent\r",
  "AC Repair & Services\r",
  "AC Wholesalers\r",
  "AUTOCAD Computer Software Dealers\r",
  "Accounting Training Institutes\r",
  "Acid Proof Tile Dealers\r",
  "Acoustic Enclosure Manufacturers\r",
  "Acrylic Carpet Dealers\r",
  "Acrylic Fabricators\r",
  "Acrylic Sign Board Manufacturers\r",
  "Admission Consultants For MBBS\r",
  "Adventure Tour Operators\r",
  "Afghani\r",
  "After Shave Lotion Dealers\r",
  "Agricultural Equipment Dealers\r",
  "Air Bed Dealers\r",
  "Air Cooler Dealers\r",
  "Air Cooler Dealers-Symphony\r",
  "Air Cooler Manufacturers\r",
  "Air Coolers On Rent\r",
  "Air Curtain Dealers\r",
  "Air Ticketing Agents\r",
  "Airport Pick & Drop Services\r",
  "Airtight Container Dealers-Tupperware\r",
  "Alarm System Dealers\r",
  "All In One Colour Computer Printer Dealers\r",
  "Almirah Locker Wholesalers\r",
  "Alternative Medicine Treatment Doctors\r",
  "Aluminium Cable Dealers\r",
  "Aluminium Cookware Dealers\r",
  "Aluminium Curtain Rod Dealers\r",
  "Aluminium Door Fitting Dealers\r",
  "Aluminium Door Manufacturers\r",
  "Aluminium Fabricators\r",
  "Aluminium Merchants\r",
  "Aluminium Sheet Dealers-Hindalco\r",
  "Aluminium Utensil Dealers\r",
  "Aluminium Wholesalers\r",
  "Aluminium Window Manufacturers\r",
  "American\r",
  "Andhra\r",
  "Animal Statue Distributors-Brass Collection\r",
  "Antique Bench Manufacturers\r",
  "Antique Collectible Dealers\r",
  "Antique Furniture Dealers\r",
  "Antique Furniture Manufacturers\r",
  "Antique Wooden Bed Dealers\r",
  "Arabic\r",
  "Architects\r",
  "Architects For Apartment\r",
  "Architects For Building\r",
  "Architects For Bungalow\r",
  "Architects For Landscape\r",
  "Army Uniform Manufacturers\r",
  "Artifact Dealers\r",
  "Artificial Vertical Wall Dealers\r",
  "Artists\r",
  "Assembled Computer Dealers\r",
  "Assembled Computer Repair & Services\r",
  "Audio Speaker Repair & Services\r",
  "Audio System Dealers\r",
  "Audio System Dealers-Pope Professional\r",
  "Audio Visual Equipments On Rent\r",
  "Automobile Battery Dealers\r",
  "Ayurvedic Body Massage Centres\r",
  "Ayurvedic Clinics\r",
  "Ayurvedic Doctors\r",
  "Ayurvedic Health Centres\r",
  "Ayurvedic Hospitals\r",
  "Ayurvedic Medicine Shops\r",
  "Ayurvedic Treatment Centres\r",
  "B Sc Nursing Colleges\r",
  "BBA Colleges\r",
  "Baby Care Product Accessory Dealers\r",
  "Baby Care Product Dealers\r",
  "Baby Care Product Manufacturers\r",
  "Baby Readymade Garment Manufacturers\r",
  "Baby Readymade Garment Retailers\r",
  "Baby Towel Dealers\r",
  "Back Pillow Dealers\r",
  "Bag Dealers\r",
  "Bag Dealers-Shalimar\r",
  "Bakeries\r",
  "Balinese Foot Massage Centres\r",
  "Balloon Decorators\r",
  "Baluster Dealers\r",
  "Bamboo Furniture Manufacturers\r",
  "Banarasi Silk Saree Manufacturers\r",
  "Banarasi Silk Saree Retailers\r",
  "Bandhani Saree Retailers\r",
  "Bands\r",
  "Banks & Finance\r",
  "Banquet Halls\r",
  "Bath MAT Dealers\r",
  "Bathroom Accessory Dealers\r",
  "Bathroom Door Dealers\r",
  "Bathroom Fitting Dealers\r",
  "Bathroom Fitting Dealers-Hindware\r",
  "Bathroom Furniture Dealers\r",
  "Battery Dealers\r",
  "Battery Distributors\r",
  "Battery Operated Auto Rickshaw Dealers\r",
  "Battery Operated Forklift On Rent\r",
  "Battery Operated Motorcycle Dealers\r",
  "Battery Operated Scooter Dealers\r",
  "Battery Operated Scooter Distributors\r",
  "Battery Operated Scooter Distributors-EKO Tejas\r",
  "Bean Bag Dealers\r",
  "Bean Bag Wholesalers\r",
  "Beauty Clinics\r",
  "Beauty Clinics For Body Sculpting\r",
  "Beauty Parlour Furniture Dealers\r",
  "Beauty Parlour Furniture Manufacturers\r",
  "Beauty Parlours\r",
  "Beauty Parlours At Home\r",
  "Beauty Parlours For Acne Treatment\r",
  "Beauty Parlours For Body Piercing\r",
  "Beauty Parlours For Bridal\r",
  "Beauty Parlours For Bridal At Home\r",
  "Beauty Parlours For Chin Bleach\r",
  "Beauty Parlours For Facial\r",
  "Beauty Parlours For Hair Bonding\r",
  "Beauty Parlours For Hair Smoothening\r",
  "Beauty Parlours For Hair Spa\r",
  "Beauty Parlours For Hair Straightening\r",
  "Beauty Parlours For Hair Style\r",
  "Beauty Parlours For Hair Treatment\r",
  "Beauty Parlours For Makeup\r",
  "Beauty Parlours For Nail Art\r",
  "Beauty Parlours For Pedicure\r",
  "Beauty Parlours For Waxing\r",
  "Beauty Salons\r",
  "Beauty Salons For Men\r",
  "Beauty Salons For Women\r",
  "Beauty Spas\r",
  "Beauty Spas For Men\r",
  "Beauty Spas For Women\r",
  "Bed Cover Dealers\r",
  "Bed Dealers\r",
  "Bed Dealers-Camabeds\r",
  "Bed Dealers-Cane Line\r",
  "Bed Dealers-Durian\r",
  "Bed Dealers-Godrej Interio\r",
  "Bed Dealers-Hastens\r",
  "Bed Dealers-Peps\r",
  "Bed Dealers-Stanley\r",
  "Bed Linen Dealers\r",
  "Bed Manufacturers\r",
  "Bed Repair & Services\r",
  "Bed Sheet Manufacturers\r",
  "Bed Sheet Retailers\r",
  "Bed Sheet Retailers-Housethis\r",
  "Bed Sheet Retailers-Portico\r",
  "Bed Sheet Stockists-Spaces\r",
  "Bed Sheet Wholesalers\r",
  "Bed Wholesalers-Auto Line\r",
  "Bedding Set Dealers\r",
  "Bedroom Furniture Dealers\r",
  "Bedroom Furniture Manufacturers\r",
  "Bedspread Manufacturers\r",
  "Bharatnatyam Costume Retailers\r",
  "Bicycle On Rent\r",
  "Bike On Rent\r",
  "Bike On Rent-Bajaj\r",
  "Bike On Rent-Hero\r",
  "Bike On Rent-Honda\r",
  "Bike On Rent-Yamaha\r",
  "Bikini Waxing Services At Home\r",
  "Birthday Cake Manufacturers\r",
  "Birthday Party Decorators\r",
  "Birthday Party Organisers\r",
  "Black Granite Dealers\r",
  "Blanket Dealers\r",
  "Blanket Distributors\r",
  "Blanket Manufacturers\r",
  "Blanket Wholesalers\r",
  "Blanket Wholesalers-Raymond\r",
  "Blazer Retailers\r",
  "Blazers On Rent\r",
  "Bleaching Liquid Manufacturers\r",
  "Blender Dealers-Tefal\r",
  "Blouse Retailers\r",
  "Boarding Schools\r",
  "Body Massage Centres\r",
  "Body Massage Centres For Seitai Treatment\r",
  "Body Massage Centres For Unisex\r",
  "Bone China Crockery Dealers\r",
  "Book Shops\r",
  "Borewell Drilling Services\r",
  "Boutiques\r",
  "Boutiques For Kids\r",
  "Brass Handicraft Dealers\r",
  "Brass Lamp Dealers\r",
  "Brass Manufacturers\r",
  "Brass Phone Wholesalers\r",
  "Brass Product Dealers\r",
  "Brass Puja Item Dealers\r",
  "Brass Puja Item Wholesalers\r",
  "Brass Puja Lamp Dealers\r",
  "Brass Utensil Dealers\r",
  "Bridal Jewellery On Rent\r",
  "Bridal Makeup Artists\r",
  "Bridal Wear Accessory Dealers\r",
  "Bridal Wear Manufacturers\r",
  "Bridal Wear On Rent\r",
  "Bridal Wear Retailers\r",
  "Broadband Internet Service Providers\r",
  "Bronze Statue Manufacturers\r",
  "Bucket Dealers\r",
  "Builders\r",
  "Builders & Developers\r",
  "Building Consultants\r",
  "Building Contractors\r",
  "Building Material Dealers\r",
  "Bulb Dealers\r",
  "Bulb Holder Manufacturers\r",
  "Bulb Manufacturers\r",
  "Bulldozers On Rent\r",
  "Bunk Bed Dealers\r",
  "Bunk Bed Manufacturers\r",
  "Burger Joints\r",
  "Burkha Retailers\r",
  "Bus On Rent\r",
  "Bus Services\r",
  "Bus Services For Mumbai Darshan\r",
  "Bus Ticketing Agents\r",
  "CA Institutes\r",
  "CBSE Schools\r",
  "CCTV Dealers\r",
  "CCTV Dealers-Panasonic\r",
  "CCTV Dealers-Zicom\r",
  "CCTV Installation Services\r",
  "CCTV Installation Services-Hikvision\r",
  "CFL Lamp Manufacturers\r",
  "Cable Dealers\r",
  "Cable Tray Dealers\r",
  "Cable Wire Dealers\r",
  "Cake Manufacturers\r",
  "Cake Shops\r",
  "Calendar Manufacturers\r",
  "Camera Dealers\r",
  "Candle Light Bulb Manufacturers\r",
  "Cane Furniture Dealers\r",
  "Cane Furniture Manufacturers\r",
  "Car Attachment Services\r",
  "Car Battery Dealers\r",
  "Car Dealers\r",
  "Car Dealers-Mercedes Benz\r",
  "Car Decorators\r",
  "Car MAT Dealers\r",
  "Car Rental\r",
  "Car Rental For Outstation\r",
  "Car Rental For Self Driven\r",
  "Car Rental-Maruti Suzuki Ertiga\r",
  "Car Repair & Services\r",
  "Car Towing Services\r",
  "Car Tyre Dealers\r",
  "Car Washing Services\r",
  "Cardiac Hospitals\r",
  "Cardiovascular Diabetologist Doctors\r",
  "Carpenters\r",
  "Carpentry Contractors For Office\r",
  "Carpet Dealers\r",
  "Carry Bag Dealers\r",
  "Cartridge Refilling Services\r",
  "Carved Wooden Door Dealers\r",
  "Casual Wear Retailers\r",
  "Caterers\r",
  "Ceiling Fan Dealers\r",
  "Cement Dealers\r",
  "Cement Dealers-ACC\r",
  "Ceramic Dealers\r",
  "Ceramic Tile Dealers\r",
  "Ceramic Tile Dealers-Kajaria\r",
  "Ceramic Tile Dealers-Somany\r",
  "Cereal Retailers\r",
  "Chaat Corners\r",
  "Chair Dealers\r",
  "Chair Manufacturers\r",
  "Chair Repair & Services\r",
  "Chair Wholesalers\r",
  "Chairs On Rent\r",
  "Chandelier Lamp Dealers\r",
  "Chanderi Saree Retailers\r",
  "Chaniya Cholis On Rent\r",
  "Chef Uniform Manufacturers\r",
  "Chemical Dealers\r",
  "Chicken Retailers\r",
  "Chiffon Saree Retailers\r",
  "Chikan Saree Retailers\r",
  "Children Beauty Parlours\r",
  "Children Furniture Dealers\r",
  "Children Hospitals\r",
  "Chocolate Mould Manufacturers\r",
  "Christmas Cake Retailers\r",
  "Christmas Santa Costumes On Rent\r",
  "Civil Contractors\r",
  "Civil Contractors For Commercial\r",
  "Civil Contractors For Mobile Tower\r",
  "Civil Engineers\r",
  "Clay Pot Manufacturers\r",
  "Clinics\r",
  "Cloth Bag Manufacturers\r",
  "Coaxial Cable Manufacturers\r",
  "Coir Dealers\r",
  "Coir Dealers-Coir Board\r",
  "Coir Mattress Manufacturers\r",
  "Coir Mattress Retailers\r",
  "College Bag Dealers\r",
  "College Uniform Retailers\r",
  "Colleges\r",
  "Colour Photocopier Dealers\r",
  "Commercial Architects\r",
  "Commercial Complexes\r",
  "Commercial Generator Dealers\r",
  "Commercial Inverter Dealers\r",
  "Commercial Kitchen Equipment Dealers\r",
  "Commercial Lighting Dealers\r",
  "Commercial Photographers\r",
  "Commercial Plywood Dealers\r",
  "Commercial Plywood Manufacturers\r",
  "Commercial Vehicle Dealers-Tata\r",
  "Commercial Vehicles On Rent\r",
  "Computer Accessory Dealers\r",
  "Computer Data Storage Device Dealers\r",
  "Computer Dealers\r",
  "Computer Dealers-Dell\r",
  "Computer Furniture Dealers\r",
  "Computer Hardware Dealers\r",
  "Computer Hardware Repair & Services\r",
  "Computer Hardware Training Institutes\r",
  "Computer Laser Printer Dealers-Kyocera\r",
  "Computer Laser Printer Toner Cartridge Dealers-HP\r",
  "Computer Printer Cartridge Dealers\r",
  "Computer Printer Cartridges Toner Reconditioning\r",
  "Computer Printer Dealers\r",
  "Computer Printer Dealers-Brother\r",
  "Computer Printer Dealers-Canon\r",
  "Computer Printer Repair & Services\r",
  "Computer Printer Repair & Services-EPSON\r",
  "Computer Printer Repair & Services-HP\r",
  "Computer Printer Repair & Services-Samsung\r",
  "Computer Printers On Rent\r",
  "Computer Printers On Rent-HP\r",
  "Computer Repair & Services\r",
  "Computer Repair & Services At Home\r",
  "Computer Repair & Services-Apple\r",
  "Computer Repair & Services-Dell\r",
  "Computer Repair & Services-HCL\r",
  "Computer Repair & Services-HP\r",
  "Computer Repair & Services-Wipro\r",
  "Computer Servers On Rent\r",
  "Computer Software Dealers\r",
  "Computer Software Developers\r",
  "Computer Training Institutes\r",
  "Computer Training Institutes For Architectural CAD\r",
  "Computers On Rent\r",
  "Computers On Rent Monthly Basis\r",
  "Concrete Vibrator Dealers\r",
  "Construction Companies\r",
  "Construction Contractors\r",
  "Construction Material Dealers\r",
  "Construction Services\r",
  "Control Panel Manufacturers\r",
  "Convent Schools\r",
  "Convocation Gowns On Rent\r",
  "Cookware Dealers\r",
  "Copper Furniture Manufacturers\r",
  "Copper Utensil Dealers\r",
  "Copper Wire Dealers\r",
  "Core Cutting Services\r",
  "Corporate Companies\r",
  "Corporate Passenger Van On Rent\r",
  "Corporate T Shirt Manufacturers\r",
  "Corporate Uniform Manufacturers\r",
  "Cosmetic Dealers\r",
  "Cosmetic Laser Surgeons\r",
  "Cosmetologist Doctors\r",
  "Costume Accessories On Rent\r",
  "Costumes On Rent\r",
  "Costumes On Rent For Dance\r",
  "Costumes On Rent For Drama\r",
  "Costumes On Rent For Fancy Dress\r",
  "Costumes On Rent For Fashion Show\r",
  "Costumes On Rent For Films\r",
  "Cot Manufacturers\r",
  "Cotton Bed Sheet Manufacturers\r",
  "Cotton Bed Sheet Retailers\r",
  "Cotton Bed Sheet Wholesalers\r",
  "Cotton Dress Material Wholesalers\r",
  "Cotton Fabric Manufacturers\r",
  "Cotton Fabric Retailers\r",
  "Cotton Fabric Wholesalers\r",
  "Cotton Manufacturers\r",
  "Cotton Mattress Manufacturers\r",
  "Cotton Mattress Retailers\r",
  "Cotton Readymade Garment Retailers-Ramraj\r",
  "Cotton Saree Retailers\r",
  "Cotton T Shirt Manufacturers\r",
  "Cotton T Shirt Wholesalers\r",
  "Cotton Wholesalers\r",
  "Counselling Services\r",
  "Couple Massage Centres\r",
  "Crane Dealers\r",
  "Crane Service Providers\r",
  "Cranes On Rent\r",
  "Cranes On Rent-Tata\r",
  "Crawler Cranes On Rent\r",
  "Crib Foam Mattress Wholesalers\r",
  "Cricket Bat Dealers\r",
  "Crimping Tool Dealers\r",
  "Crochet Bed Sheet Retailers\r",
  "Crockery Dealers\r",
  "Cupboard Manufacturers\r",
  "Cupping Therapy Centres\r",
  "Curtain Dealers\r",
  "Curtain Dealers-Kurl On\r",
  "Curtain Designing Services\r",
  "Curtain Fabric Manufacturers\r",
  "Curtain Manufacturers\r",
  "Curtain Strip Dealers\r",
  "Cushion Dealers\r",
  "Cushion MAT Dealers\r",
  "Cushion Manufacturers\r",
  "Cushion Wholesalers-Marvel\r",
  "Customised Bed Sheet Wholesalers\r",
  "Cutlery Dealers\r",
  "Cycling Jersey Manufacturers\r",
  "DJ System On Rent\r",
  "DTH TV Broadcast Service Providers\r",
  "DTH TV Broadcast Service Providers-Tata Play\r",
  "DTH TV Recharge Coupon Dealers-Airtel Digital TV\r",
  "Dance Classes\r",
  "Decoration Materials On Rent\r",
  "Decorative LED Bulb Manufacturers\r",
  "Decorative Lamp Manufacturers\r",
  "Decorative Light Dealers\r",
  "Decorative Light Dealers-Ankur\r",
  "Decorative Light Fitting Dealers\r",
  "Decorative Plywood Dealers\r",
  "Decorative Stretch Ceiling Dealers\r",
  "Decorative Wall Paper Dealers\r",
  "Decorators\r",
  "Decorators Stage Backdrop\r",
  "Dental Clinics\r",
  "Dentists\r",
  "Departmental Stores\r",
  "Dermatologists\r",
  "Designer Bed Sheet Retailers\r",
  "Designer Furniture Dealers\r",
  "Designer Readymade Garment Retailers\r",
  "Designer Saree Retailers\r",
  "Designer Wall Paper Dealers\r",
  "Designer Women Kurti Wholesalers\r",
  "Diabetologist Doctors\r",
  "Diagnostic Centres\r",
  "Dialysis Centres\r",
  "Diesel Generator Dealers-Cat\r",
  "Diesel Generators On Rent\r",
  "Diet Food Restaurants\r",
  "Dietitians For Weight Gain\r",
  "Digital Marketing Services\r",
  "Digital Photographers\r",
  "Digital Video Projector On Rent\r",
  "Dining Chair Manufacturers\r",
  "Dining Table Exporters\r",
  "Dining Table Manufacturers\r",
  "Diploma In Mechanical Engineering Correspondence Institutes\r",
  "Disc Jockey\r",
  "Display Rack Dealers\r",
  "Disposable Bed Sheet Dealers\r",
  "Disposable Product Dealers\r",
  "Disposal Product Exporters\r",
  "Domestic Tour Operators\r",
  "Domestic Tour Packages\r",
  "Donut Retailers\r",
  "Door Dealers\r",
  "Door MAT Dealers\r",
  "Door Manufacturers\r",
  "Door Mosquito Net Dealers\r",
  "Dosa Outlets\r",
  "Double Bed Manufacturers\r",
  "Dress Material Retailers\r",
  "Dress Material Retailers-Garden Vareli\r",
  "Dressing Table Manufacturers\r",
  "Driver Service Agents For Hourly Basis\r",
  "Dry Cleaners\r",
  "Ductable AC Repair & Services\r",
  "Duvet Distributors\r",
  "ENT Hospitals\r",
  "Earthmovers On Rent\r",
  "Earthmovers On Rent-JCB\r",
  "Education Consultants\r",
  "Education Consultants For B Ed\r",
  "Education Consultants For Btech\r",
  "Education Consultants For MBBS\r",
  "Education Consultants For Medical In Abroad\r",
  "Educational Institutes\r",
  "Educational Institutions\r",
  "Educational Toy Dealers\r",
  "Educational Trusts\r",
  "Electric Chimney Dealers\r",
  "Electric Chimney Manufacturers\r",
  "Electric Chimney Wholesalers\r",
  "Electric Vehicle Dealers\r",
  "Electric Wire Dealers\r",
  "Electric Wire Scrap Buyers\r",
  "Electrical Contractors\r",
  "Electrical Contractors For Building\r",
  "Electrical Control Panel Dealers\r",
  "Electrical Goods Dealers\r",
  "Electrical Goods Dealers-ABB\r",
  "Electrical Goods Dealers-Anchor\r",
  "Electrical Goods Dealers-Havells\r",
  "Electrical Goods Dealers-Surya\r",
  "Electrical Goods Wholesalers\r",
  "Electrical Lighting Dealers-Philips\r",
  "Electrical Panel Manufacturers\r",
  "Electrical Shops\r",
  "Electrical Shops, Power Tool Dealers\r",
  "Electrical Transformer Manufacturers\r",
  "Electricians\r",
  "Electronic Accessory Wholesalers\r",
  "Electronic Component Dealers\r",
  "Electronic Goods Showrooms\r",
  "Electronic Goods Wholesalers\r",
  "Elevator Repair & Services\r",
  "Embroidered Bed Sheet Retailers\r",
  "Embroidery Material Retailers\r",
  "Emergency Light Dealers\r",
  "Energy Saving Equipment Manufacturers\r",
  "Energy Saving Lamp Manufacturers\r",
  "Engine Spare Part Manufacturers\r",
  "Engineering Colleges\r",
  "English Medium Schools\r",
  "Entertainment Companies\r",
  "Ethnic Sofa Dealers\r",
  "Ethnic Wear Retailers-Ethnicity\r",
  "Event Decorators\r",
  "Event Management Companies\r",
  "Event Management Companies For Celebrity\r",
  "Event Management Companies For Video Conferencing\r",
  "Event Organisers\r",
  "Event Organisers For Birthday Party\r",
  "Event Organisers For Dance Parties\r",
  "Event Organisers For New Year Party\r",
  "Event Organisers For Theme Parties\r",
  "Event Organisers For Wedding\r",
  "Event Venues\r",
  "Excavators On Rent-JCB\r",
  "Exhaust Fan Dealers\r",
  "Exhibition Stalls On Rent\r",
  "Exterior Designers\r",
  "Eye Clinics\r",
  "Eye Hospitals\r",
  "Fabric Manufacturers\r",
  "Fabric Retailers\r",
  "Fabric Wholesalers\r",
  "Fabrication Contractors\r",
  "Fabricators\r",
  "Factory Furniture Manufacturers\r",
  "Factory Uniform Manufacturers\r",
  "False Ceiling Contractors\r",
  "Fan Dealers\r",
  "Fan Dealers-Bajaj\r",
  "Fan Regulator Distributors-Goldmedal\r",
  "Fancy Bag Dealers\r",
  "Fancy Dress Costume Retailers\r",
  "Fancy Dress Costume Wholesalers\r",
  "Fancy Dress Material Retailers\r",
  "Fancy Light Dealers\r",
  "Fancy Light Manufacturers\r",
  "Fancy Light Wholesalers\r",
  "Fashion Accessories On Rent\r",
  "Fashion Designers\r",
  "Fashion Designing Institutes\r",
  "Fashion Photographers\r",
  "Feeding Pillow Dealers\r",
  "Finance Consultants\r",
  "Fitness Centres\r",
  "Flameproof Control Panel Manufacturers\r",
  "Flood Fitting Dealers-Crompton Greaves\r",
  "Floor Carpet Dealers\r",
  "Floor MAT Dealers\r",
  "Floor Wiper Wholesalers\r",
  "Florists\r",
  "Flower Decorators\r",
  "Flower Decorators For Function\r",
  "Foam Mattress Manufacturers\r",
  "Folding Bed Dealers\r",
  "Folding Bed Manufacturers\r",
  "Food Packaging Material Dealers\r",
  "Foot Reflexology Massage Services\r",
  "Forklifts On Hire\r",
  "Formal Shirt Manufacturers\r",
  "Franchise Consultants\r",
  "Freelance Makeup Artists\r",
  "Fried Chicken Delivery Restaurants\r",
  "Fried Chicken Restaurants\r",
  "Fruit Plant Nurseries\r",
  "Furnishing Retailers\r",
  "Furniture Accessory Dealers\r",
  "Furniture Cot Manufacturers\r",
  "Furniture Dealers\r",
  "Furniture Dealers (Economy)\r",
  "Furniture Dealers-Durian\r",
  "Furniture Dealers-Godrej Interio\r",
  "Furniture Dealers-Nilkamal\r",
  "Furniture Dealers-Sauder\r",
  "Furniture Dealers-Spacewood\r",
  "Furniture Dealers-Supreme\r",
  "Furniture Dealers-Zuari\r",
  "Furniture Fitting Dealers\r",
  "Furniture Fitting Hardware Dealers-Hettich\r",
  "Furniture Importers\r",
  "Furniture Manufacturers\r",
  "Furniture Wholesalers\r",
  "Furnitures On Rent\r",
  "Gadwal Saree Retailers\r",
  "Gaming Zones\r",
  "Ganpati Idol Dealers\r",
  "Garages\r",
  "Garba Costumes On Rent\r",
  "Garden Furniture Dealers\r",
  "Garden Furniture Manufacturers\r",
  "Garment Accessory Dealers-All\r",
  "Gas Regulator Dealers\r",
  "Gas Stove Dealers\r",
  "Gas Stove Repair & Services-Prestige\r",
  "Gate Fabricators\r",
  "Gate Manufacturers\r",
  "General Physician Doctors\r",
  "General Stores\r",
  "Generator Dealers\r",
  "Generator Dealers-Honda\r",
  "Generator Dealers-Kirloskar\r",
  "Generator Dealers-Mahindra\r",
  "Generator Distributors\r",
  "Generator Repair & Services\r",
  "Generators On Rent\r",
  "Generators On Rent For Functions\r",
  "Gift Basket Wholesalers\r",
  "Gift Box Manufacturers\r",
  "Gift Shops\r",
  "Girls Colleges\r",
  "Glass Crockery Dealers\r",
  "Glass Dealers\r",
  "Glass Job Works\r",
  "God Idol Dealers\r",
  "God Idol Manufacturers\r",
  "Gold Leafing Job Works\r",
  "Goods Carrier On Rent\r",
  "Government Hostels\r",
  "Grill Restaurants\r",
  "Grocery Stores\r",
  "Groom Makeup Artists\r",
  "Grooming Classes\r",
  "Guest Houses\r",
  "Gynaecologist & Obstetrician Doctors\r",
  "HDPE Plastic Tarpaulin Manufacturers\r",
  "HDPE Tarpaulin Dealers\r",
  "Hair Colour Highlight Services\r",
  "Hair Fixer Dealers\r",
  "Hair Loss Doctors\r",
  "Hair Stylist For Men\r",
  "Hair Stylists\r",
  "Hair Transplant Doctors\r",
  "Hair Treatment Clinics\r",
  "Halal Restaurants\r",
  "Hand Tool Dealers\r",
  "Handicraft Exporters\r",
  "Handicraft Item Dealers\r",
  "Handicraft Item Manufacturers\r",
  "Handloom Bed Sheet Retailers\r",
  "Handloom Bed Sheet Wholesalers\r",
  "Handloom Bedspread Retailers\r",
  "Handloom Curtain Retailers\r",
  "Handloom Retailers\r",
  "Hardware Dealers\r",
  "Hardware Shops\r",
  "Health Care Centres\r",
  "Heater Dealers\r",
  "Hifz Quran Classes\r",
  "Holistic Medicine Practitioners\r",
  "Home Appliance Dealers\r",
  "Home Appliance Dealers-Bajaj\r",
  "Home Appliance Dealers-Butterfly\r",
  "Home Appliance Dealers-Inalsa\r",
  "Home Appliance Dealers-Milton\r",
  "Home Appliance Dealers-Prestige\r",
  "Home Decor Dealers\r",
  "Home Decor Manufacturers\r",
  "Home Decorative Item Dealers\r",
  "Home Decorative Item Dealers-Bedford Home\r",
  "Home Decorative Item Dealers-Bianca\r",
  "Home Delivery Restaurants\r",
  "Home Furnishing Manufacturers\r",
  "Home Furnishing Retailers\r",
  "Home Furniture Dealers\r",
  "Home Stays\r",
  "Home Theatre System Repair & Services\r",
  "Home Tutors\r",
  "Home Tutors For Accounts\r",
  "Home Tutors For CBSE Class X Maths\r",
  "Home Tutors For Quran\r",
  "Homeopathic Clinics\r",
  "Homeopathic Doctors\r",
  "Homeopathic Doctors For Cancer\r",
  "Homeopathic Hospitals\r",
  "Homeopathic Medicine Retailers\r",
  "Homeopathic Physician Doctors\r",
  "Hoodie Manufacturers\r",
  "Hospital Bed Dealers\r",
  "Hospital Bed Manufacturers\r",
  "Hospital Equipment Dealers\r",
  "Hospital Furniture Dealers\r",
  "Hospital Furniture Manufacturers\r",
  "Hospital Steel Furniture Manufacturers\r",
  "Hospital Uniform Manufacturers\r",
  "Hospital Uniform Retailers\r",
  "Hospitals\r",
  "Hostel For Boy Students\r",
  "Hostel For Girl Students\r",
  "Hostel For Students\r",
  "Hostels\r",
  "Hostels For Men\r",
  "Hostels For Women\r",
  "Hostels For Working Men\r",
  "Hostels For Working Women\r",
  "Hotel Bed Sheet Manufacturers\r",
  "Hotel Furniture Dealers\r",
  "Hotel Furniture Manufacturers\r",
  "Hotel Kitchen Equipment Dealers\r",
  "Hotel Linen Manufacturers\r",
  "Hotel Uniform Manufacturers\r",
  "Hotel Uniform Retailers\r",
  "Hotels\r",
  "Household Item Dealers\r",
  "Housekeeping Services\r",
  "Hydra Cranes On Hire\r",
  "Hydraulic Cranes On Hire\r",
  "Hydraulic Cylinder Manufacturers\r",
  "IELTS Tutorials\r",
  "ITI Institutes\r",
  "Idol Dealers\r",
  "Idol Manufacturers\r",
  "Imitation Jewellery On Rent\r",
  "Imported Furniture Dealers\r",
  "Imported Marble Dealers\r",
  "Imported Modular Kitchen Dealers\r",
  "Indian Restaurants\r",
  "Induction Cooker Dealers-Usha\r",
  "Industrial Areas\r",
  "Industrial Construction Companies\r",
  "Industrial Generator Dealers\r",
  "Industrial Hooter Manufacturers\r",
  "Industrial LED Light Dealers\r",
  "Industrial Uniform Manufacturers\r",
  "Inexpensive Restaurants Below Rs 500\r",
  "Institutes\r",
  "Institutes For B Pharma\r",
  "Institutes For BBA In Aviation\r",
  "Intelligent Lights On Rent\r",
  "Interior Architects\r",
  "Interior Decorators\r",
  "Interior Decorators For Furniture\r",
  "Interior Decorators For Hotel\r",
  "Interior Decorators For Kitchen\r",
  "Interior Decorators For Office\r",
  "Interior Decorators For Residences\r",
  "Interior Designers\r",
  "Interior Designers For Apartment\r",
  "Interior Designers For Bungalow\r",
  "Interior Designers For Call Centre\r",
  "Interior Designers For Furniture\r",
  "Interior Designers For Industrial\r",
  "Interior Designers For Office\r",
  "Interior Designers For Shops\r",
  "Interior Hardware Dealers-Hettich\r",
  "International Tour Packages\r",
  "Internet Service Providers\r",
  "Inverter Dealers\r",
  "Inverter Manufacturers\r",
  "Iron Bed Manufacturers\r",
  "Iron Garden Bench Manufacturers\r",
  "Iron Gate Manufacturers\r",
  "Iron Plate Dealers\r",
  "Iron Rack Manufacturers\r",
  "Iron Rod Dealers\r",
  "Iron Rod Wholesalers\r",
  "Islamic Schools\r",
  "JCB Hire\r",
  "Jacuzzi Bath Services\r",
  "Jeans Manufacturers\r",
  "Jewellery On Rent\r",
  "Jewellery Showrooms\r",
  "Jute Bag Manufacturers\r",
  "Kadai Dealers\r",
  "Kanchipuram Silk Saree Retailers\r",
  "Kanjivaram Saree Retailers\r",
  "Kebab Restaurants\r",
  "Kids Bed Manufacturers\r",
  "Kids Bed Sheet Dealers\r",
  "Kids Costumes On Rent For Dance\r",
  "Kids Furniture Manufacturers\r",
  "Kids Readymade Garment Retailers\r",
  "Kids T Shirt Manufacturers\r",
  "King Bed Dealers\r",
  "King Chair Manufacturers\r",
  "Kitchen Appliance Dealers\r",
  "Kitchen Appliance Dealers-Prestige\r",
  "Kitchen Equipment Dealers\r",
  "Kitchen Equipment Manufacturers\r",
  "Kitchen Furniture Dealers\r",
  "Kitchen Trolley Dealers\r",
  "Kitchen Trolley Manufacturers\r",
  "Kitchenware Dealers\r",
  "Knitwear Manufacturers\r",
  "Kurta Pyjama On Rent\r",
  "Kurta Retailers\r",
  "LCD Projectors On Rent\r",
  "LED Bulb Dealers\r",
  "LED Dealers\r",
  "LED Fancy Light Dealers\r",
  "LED Halogen Light Manufacturers\r",
  "LED Lamp Dealers\r",
  "LED Light Dealers\r",
  "LED Light Dealers-Halonix\r",
  "LED Light Dealers-Havells\r",
  "LED Light Dealers-Nuvo\r",
  "LED Light Dealers-Osram\r",
  "LED Light Dealers-Philips\r",
  "LED Light Manufacturers\r",
  "LED Light Wholesalers\r",
  "LED Panel Light Dealers\r",
  "LED Panel Light Dealers-Polycab\r",
  "LED Spot Light Dealers\r",
  "LED Square Downlight Manufacturers\r",
  "LED Street Light Dealers\r",
  "LED Street Light Dealers-Orient Electric\r",
  "LED Street Light Manufacturers\r",
  "LED Strip Light Dealers\r",
  "LED TV Dealers\r",
  "LED Track Light Dealers-Samson\r",
  "LED Video Wall On Rent\r",
  "LED Walls On Rent\r",
  "LED Well Glass Wholesalers\r",
  "Lab Furniture Dealers\r",
  "Lab Furniture Manufacturers\r",
  "Laboratory Testing Services\r",
  "Lamp Dealers-Osram\r",
  "Lamp Manufacturers\r",
  "Landscape Design Consultants\r",
  "Language Classes\r",
  "Language Classes For Arabic\r",
  "Language Classes For English\r",
  "Language Classes For English Conversation\r",
  "Language Classes For German\r",
  "Language Classes For Urdu\r",
  "Laparoscopic Surgeons\r",
  "Laptop Dealers\r",
  "Laptop Repair & Services\r",
  "Laptop Repair & Services-Dell\r",
  "Laptop Repair & Services-HP\r",
  "Laptop Repair & Services-Toshiba\r",
  "Laptop Table Manufacturers\r",
  "Laptop Wholesalers\r",
  "Laptops On Rent\r",
  "Laptops On Rent-Dell\r",
  "Laptops On Rent-IBM\r",
  "Laser Hair Treatment Clinics\r",
  "Laser Treatment Centers\r",
  "Laundry Services\r",
  "Leather Bag Dealers\r",
  "Leather Sofa Dealers\r",
  "Leather Sofa Manufacturers\r",
  "Leather Sofa Repair & Services\r",
  "Lebanese\r",
  "Lebanese, American\r",
  "Lehenga On Rent\r",
  "Library Furniture Dealers\r",
  "Light Fitting Dealers\r",
  "Lighting Dealers\r",
  "Lighting Dealers-LedLum\r",
  "Lighting Dealers-Philips\r",
  "Lighting Fixture Dealers-Philips\r",
  "Lock Dealers\r",
  "Lodges\r",
  "Logistic Services\r",
  "Logistic Services For Domestic\r",
  "Luggage Bag Dealers\r",
  "Lunch Box Dealers\r",
  "Luxury Bus On Rent\r",
  "Luxury Car Rental\r",
  "MDF Board Furniture Manufacturers\r",
  "Makeup Artists\r",
  "Mandap Decorators\r",
  "Mandi Restaurants\r",
  "Marble Tile Dealers\r",
  "Marine Health Check UP Centres\r",
  "Markets\r",
  "Masala Powder Dealers\r",
  "Masks On Rent\r",
  "Massage Services For Health Benefits\r",
  "Matching Centers\r",
  "Maternity Hospitals\r",
  "Mattress Dealers\r",
  "Mattress Dealers-Centuary\r",
  "Mattress Dealers-Duroflex\r",
  "Mattress Dealers-Kurl On\r",
  "Mattress Dealers-Peps\r",
  "Mattress Dealers-Sleepwell\r",
  "Mattress Distributors-Peps\r",
  "Mattress Manufacturers\r",
  "Mattress Wholesalers\r",
  "Mattress Wholesalers-Sleepwell\r",
  "Medical Apron Retailers\r",
  "Medical Equipment Dealers\r",
  "Medical Equipment Manufacturers\r",
  "Mehendi Artists At Home\r",
  "Mehendi Dealers\r",
  "Memory Foam Mattress Retailers\r",
  "Memory Foam Pillow Wholesalers\r",
  "Men Beauty Parlours\r",
  "Men Beauty Parlours (Economy)\r",
  "Men Casual Shirt Wholesalers\r",
  "Men Readymade Garment Retailers\r",
  "Men Readymade Garment Retailers-All The Plus Size\r",
  "Men Shoe Dealers\r",
  "Men T Shirt Manufacturers\r",
  "Men Undergarment Retailers-Jockey\r",
  "Metal Bed Wholesalers\r",
  "Metal Dealers\r",
  "Middle Eastern\r",
  "Mini Bus On Rent\r",
  "Mini Truck On Rent For Outstation\r",
  "Mini Trucks On Rent\r",
  "Mini Trucks On Rent-Tata Ace\r",
  "Mini Trucks On Rent-Tata Ace Zip\r",
  "Mist Fan On Rent\r",
  "Mixer Grinder Dealers\r",
  "Mobile Generators On Rent\r",
  "Mobile Phone Accessory Repair & Services\r",
  "Mobile Phone Dealers\r",
  "Mobile Phone Dealers-Samsung\r",
  "Mobile Phone Dealers-Sony\r",
  "Mobile Phone Repair & Services\r",
  "Mobile Phone Repair & Services-Lenovo\r",
  "Mobile Phone Repair & Services-Oneplus\r",
  "Moderate Restaurants Rs 500 To Rs 1000\r",
  "Modular False Ceiling Contractors\r",
  "Modular Furniture Dealers\r",
  "Modular Furniture Manufacturers\r",
  "Modular Kitchen Dealers\r",
  "Modular Kitchen Dealers (Economy)\r",
  "Modular Kitchen Furniture Dealers\r",
  "Modular Kitchen Furniture Manufacturers\r",
  "Modular Kitchen Manufacturers\r",
  "Modular Kitchen Wholesalers\r",
  "Modular Office Furniture Dealers\r",
  "Modular Switch Dealers\r",
  "Modular Switch Dealers-ABB\r",
  "Money Transfer Agencies\r",
  "Mosques\r",
  "Mosquito Net Dealers\r",
  "Mosquito Net Manufacturers\r",
  "Motor Grader Dealers\r",
  "Motor Pump Dealers\r",
  "Motorcycle Dealers\r",
  "Motorcycle Dealers-Bajaj\r",
  "Motorcycle Dealers-Honda\r",
  "Motorcycle Dealers-Suzuki\r",
  "Motorcycle Repair & Services\r",
  "Motorcycle Repair & Services-Bajaj (Authorised)\r",
  "Moulded Furniture Dealers\r",
  "Multi Boring Machine Manufacturers\r",
  "Multimedia Projectors On Rent\r",
  "Musical Water Fountain Dealers\r",
  "NCC Uniform Retailers\r",
  "Naga\r",
  "Natural Stone Dealers\r",
  "Neurologists\r",
  "Newborn Baby Garment Retailers\r",
  "Non Destructive Testing Services\r",
  "Non Stick Cookware Manufacturers\r",
  "Nursing Homes\r",
  "Octagonal Pole Manufacturers\r",
  "Office Chair Dealers\r",
  "Office Chair Manufacturers\r",
  "Office Furniture Dealers\r",
  "Office Furniture Manufacturers\r",
  "Office Furnitures On Rent\r",
  "Office Steel Furniture Dealers\r",
  "Office Steel Furniture Manufacturers\r",
  "Office Table Dealers\r",
  "Offices On Rent\r",
  "Online Education\r",
  "Online Education Consultants\r",
  "Online IAS Coaching\r",
  "Online Maths Classes\r",
  "Online Passport Agents\r",
  "Online Quran Classes\r",
  "Online Training Institutes For Diploma In Health Education\r",
  "Online UPS Dealers\r",
  "Online Websites\r",
  "Open Trucks On Rent\r",
  "Ophthalmologists\r",
  "Opticians\r",
  "Optometrist Doctors\r",
  "Orchestra Bands\r",
  "Orthopaedic Doctors\r",
  "Orthopaedic Mattress Retailers\r",
  "Outdoor LED Screens On Rent\r",
  "Overseas Education Consultant For MBBS In Egypt\r",
  "Overseas Education Consultants\r",
  "Overseas Education Consultants For MBBS In Abroad\r",
  "Overseas Placement Services For Travel Industry (For Employers)\r",
  "PVC Carpet Dealers\r",
  "Packaging Machine Manufacturers\r",
  "Packers And Movers\r",
  "Paediatricians\r",
  "Paint Dealers\r",
  "Paint Dealers-Dulux\r",
  "Panel Board Manufacturers\r",
  "Panel Light House Wholesalers\r",
  "Pani Puri Centres\r",
  "Paper Bag Dealers\r",
  "Paper Bag Manufacturers\r",
  "Paper Plate Dealers\r",
  "Party Decorators\r",
  "Party Makeup Artists\r",
  "Patch Work Quilt Dealers\r",
  "Pathology Labs\r",
  "Paying Guest Accommodations\r",
  "Paying Guest Accommodations For Men\r",
  "Paying Guest Accommodations For Women\r",
  "Personalized Gift Shops\r",
  "Petticoat Manufacturers\r",
  "Photo Frame Dealers\r",
  "Photo Studios\r",
  "Photocopier Dealers\r",
  "Photocopiers On Rent\r",
  "Photocopiers On Rent-Canon\r",
  "Photographers\r",
  "Photographers For Function\r",
  "Physiotherapy Centres\r",
  "Pillow Dealers\r",
  "Pillow Dealers-Duroflex\r",
  "Pillow Dealers-Kurl On\r",
  "Pillow Dealers-Recron\r",
  "Pillow Dealers-Relaxwell\r",
  "Pillow Dealers-Sleepwell\r",
  "Pillow Manufacturers\r",
  "Pine Wood Dealers\r",
  "Placement Services (Candidate)\r",
  "Placement Services For Travel Industry (Candidate)\r",
  "Plastic Bag Dealers\r",
  "Plastic Bottle Dealers\r",
  "Plastic Bottle Manufacturers\r",
  "Plastic Box Dealers\r",
  "Plastic Chair Dealers-Nilkamal\r",
  "Plastic Chairs On Rent\r",
  "Plastic Container Dealers\r",
  "Plastic Container Dealers-Cello\r",
  "Plastic Container Distributors\r",
  "Plastic Container Manufacturers\r",
  "Plastic Dealers\r",
  "Plastic Furniture Dealers\r",
  "Plastic Household Item Dealers\r",
  "Plastic Household Item Wholesalers\r",
  "Plastic Manufacturers\r",
  "Plastic Moulding Household Item Wholesalers\r",
  "Plastic Product Dealers\r",
  "Plate Dealers\r",
  "Plating Services\r",
  "Playground Equipment Manufacturers\r",
  "Plazas & Arcades\r",
  "Plumbers\r",
  "Plumbing Contractors\r",
  "Plywood Dealers\r",
  "Plywood Manufacturers\r",
  "Polyclinics\r",
  "Polyester Yarn Manufacturers\r",
  "Polyfill Fiber Manufacturers\r",
  "Polytechnic Institutes\r",
  "Pop False Ceiling Contractors\r",
  "Portable Generator Dealers\r",
  "Power Generator Manufacturers\r",
  "Power Tool Dealers\r",
  "Pressure Cooker Dealers\r",
  "Printed Bed Cover Dealers\r",
  "Printed Bed Sheet Retailers\r",
  "Printing Press\r",
  "Private Hospitals\r",
  "Projector Dealers\r",
  "Projector Repair & Services\r",
  "Projectors On Rent\r",
  "Promotional Umbrella Manufacturers\r",
  "Property Valuers\r",
  "Provident Fund Agents\r",
  "Public Hospitals\r",
  "Public Schools\r",
  "Puja Item Dealers\r",
  "Puja Item Dealers-Hari Darshan\r",
  "Puja Item Wholesalers\r",
  "Pure Steam Generator Manufacturers\r",
  "Queen Size Bed Mattress Dealers-Peps\r",
  "Quick Bites\r",
  "Quick Bites Outlets\r",
  "Quilt Dealers\r",
  "Quilt Manufacturers\r",
  "Quilt Mattress Dealers\r",
  "Quran Classes\r",
  "RCC Door Frame Manufacturers\r",
  "RTO Consultants\r",
  "RTO Office\r",
  "Rack Dealers\r",
  "Rack Manufacturers\r",
  "Railway Enquiry Services\r",
  "Rainwear Manufacturers\r",
  "Readymade Garment Accessory Retailers\r",
  "Readymade Garment Manufacturers\r",
  "Readymade Garment Retailers\r",
  "Readymade Garment Retailers-And\r",
  "Readymade Garment Wholesalers\r",
  "Readymade Garments On Rent\r",
  "Refractory Manufacturers\r",
  "Refrigerator Repair & Services\r",
  "Remote Sensing Curtain Dealers\r",
  "Residence Interior Designers\r",
  "Residential Builders\r",
  "Residual Current Circuit Breaker Dealers-Orient Electric\r",
  "Resorts\r",
  "Restaurants\r",
  "Revolving Chair Dealers\r",
  "Rexine Foam Dealers\r",
  "River Sand Dealers\r",
  "Ro Water Purifier Dealers\r",
  "Ro Water Purifier Repair & Services\r",
  "Road Building Material Dealers\r",
  "Road Rollers On Rent\r",
  "Roller Blind Manufacturers\r",
  "Roofing Sheet Dealers\r",
  "Room Heater Dealers\r",
  "Rosewood Furniture Dealers\r",
  "Rubber Wood Manufacturers\r",
  "Russian Spas\r",
  "SAP Training Institutes\r",
  "SS Fabricators\r",
  "Safe Dealers\r",
  "Safe Dealers-Godrej\r",
  "Safety Sunglass Dealers\r",
  "Salons\r",
  "Sandwich Stalls\r",
  "Sanitaryware Dealers\r",
  "Sanitaryware Dealers-Hindware\r",
  "Saree Retailers\r",
  "Saree Wholesalers\r",
  "Saw Mills\r",
  "Scaffolding On Rent\r",
  "School Belt Manufacturers\r",
  "School Bench Manufacturers\r",
  "School Desk Manufacturers\r",
  "School Furniture Manufacturers\r",
  "School Steel Furniture Manufacturers\r",
  "School Uniform Manufacturers\r",
  "School Uniform Retailers\r",
  "School Uniform Wholesalers\r",
  "Schools\r",
  "Scooter Dealers\r",
  "Scooter Dealers-Bajaj\r",
  "Scooters On Rent\r",
  "Scout Uniform Retailers\r",
  "Search Engine Optimization Services\r",
  "Second Hand Car Buyers-Toyota Innova\r",
  "Second Hand Car Dealers\r",
  "Second Hand Car Dealers-Audi\r",
  "Second Hand Car Dealers-Chevrolet\r",
  "Second Hand Car Dealers-Ford\r",
  "Second Hand Car Dealers-Honda\r",
  "Second Hand Car Dealers-Hyundai\r",
  "Second Hand Car Dealers-Maruti Suzuki\r",
  "Second Hand Car Dealers-Toyota\r",
  "Second Hand Commercial Vehicle Dealers\r",
  "Second Hand Furniture Buyers\r",
  "Second Hand Furniture Dealers\r",
  "Second Hand Generator Dealers\r",
  "Second Hand Laptop Dealers\r",
  "Second Hand Laptop Dealers-Dell\r",
  "Second Hand Motorcycle Dealers\r",
  "Second Hand Vehicle Buyers\r",
  "Security Guard Uniform Manufacturers\r",
  "Sewing Machine Dealers\r",
  "Sexologist Doctors\r",
  "Shamiana Contractors\r",
  "Shamiana On Rent\r",
  "Shamiyana Dealers\r",
  "Shamiyana Manufacturers\r",
  "Shed Fabricators\r",
  "Sherwanis On Rent\r",
  "Shoe Dealers\r",
  "Shoe Distributors\r",
  "Shop Furniture Dealers\r",
  "Shopping Complexes\r",
  "Shopping Malls\r",
  "Shower Curtain Dealers\r",
  "Sichuan\r",
  "Sign Board Dealers\r",
  "Silent Diesel Generator Wholesalers\r",
  "Silk Bedding Set Manufacturers\r",
  "Silver Plate Wholesalers\r",
  "Single Bed Dealers\r",
  "Single Bed Wholesalers-Off The Shelf\r",
  "Sink Mixer Dealers-Parryware\r",
  "Skin Care Clinics\r",
  "Sliding Window Contractors\r",
  "Slotted Angle Rack Dealers\r",
  "Slotted Angle Rack Manufacturers\r",
  "Slotted Angle Steel Rack Manufacturers\r",
  "Snacks Retailers\r",
  "Socks Manufacturers\r",
  "Sofa Cover Dealers-Raymond\r",
  "Sofa Cum Bed Dealers\r",
  "Sofa Cum Bed Manufacturers\r",
  "Sofa Cum Bed Mattress Dealers\r",
  "Sofa Cum Bed Wholesalers\r",
  "Sofa Dealers\r",
  "Sofa Lining Services\r",
  "Sofa Making Fabric Retailers\r",
  "Sofa Manufacturers\r",
  "Sofa Repair & Services\r",
  "Sofa Set Manufacturers\r",
  "Sofa Set Repair & Services\r",
  "Sofa Wholesalers\r",
  "Solapuri Bed Sheet Retailers\r",
  "Solar Geyser Wholesalers-Ashirvad\r",
  "Solar Light Dealers\r",
  "Solar Panel Dealers\r",
  "Solar Panel Installation Services\r",
  "Solar Panel Manufacturers\r",
  "Solar Power Plant Manufacturers\r",
  "Solar Street Light Manufacturers\r",
  "Sound System Dealers-Ahuja\r",
  "Sound Systems On Hire\r",
  "Sound Systems On Rent-JBL\r",
  "Spanish\r",
  "Sports Goods Dealers\r",
  "Sports Shoe Dealers\r",
  "Sports T Shirt Manufacturers\r",
  "Sportswear Manufacturers\r",
  "Sportswear Retailers\r",
  "Spot Light Dealers\r",
  "Spring Mattress Retailers\r",
  "Stage Decorators\r",
  "Stainless Steel Dealers-Jindal\r",
  "Stainless Steel Furniture Dealers\r",
  "Stainless Steel Furniture Manufacturers\r",
  "Stainless Steel Kitchen Equipment Manufacturers\r",
  "Stainless Steel Kitchenware Dealers\r",
  "Stainless Steel Table Manufacturers\r",
  "Stainless Steel Utensil Dealers\r",
  "Stainless Steel Wire Mesh Dealers\r",
  "State Board Schools\r",
  "Steam Iron Dealers\r",
  "Steel Bed Manufacturers\r",
  "Steel Chair Manufacturers\r",
  "Steel Cupboard Manufacturers\r",
  "Steel Dealers\r",
  "Steel Fabricators\r",
  "Steel Furniture Dealers\r",
  "Steel Furniture Manufacturers\r",
  "Steel Merchants\r",
  "Steel Product Dealers\r",
  "Steel Rack Manufacturers\r",
  "Steel Storewell Dealers\r",
  "Steel Storewell Dealers-Tata Steel\r",
  "Steel Storewell Manufacturers\r",
  "Steel Table Dealers\r",
  "Stock Brokers\r",
  "Store Design Services\r",
  "Storewell Dealers\r",
  "Storewell Manufacturers\r",
  "Storewell Repair & Services\r",
  "Street Light Dealers\r",
  "Street Light Manufacturers\r",
  "Street Light Pole Manufacturers\r",
  "Street Light Pole Wholesalers\r",
  "Study Table Dealers\r",
  "Submersible Pump Dealers\r",
  "Submersible Pump Repair & Services\r",
  "Suit Fabric Dealers-Raymond\r",
  "Suit Retailers\r",
  "Suit Wholesalers\r",
  "Suits On Rent\r",
  "Supermarkets\r",
  "Supermarkets Home Delivery\r",
  "Surveyors\r",
  "Swedish Body Massage Services\r",
  "Sweet Shops\r",
  "Swimming Pools\r",
  "Swing Dealers\r",
  "Switch Dealers\r",
  "Switch Dealers-Anchor\r",
  "Switch Dealers-Legrand\r",
  "Switchgear Dealers\r",
  "T B Relief Centres\r",
  "T Shirt Manufacturers\r",
  "T Shirt Printing Services\r",
  "TV Dealers\r",
  "Table Manufacturers\r",
  "Tables On Rent\r",
  "Tailors\r",
  "Tailors For Kurta Pajama\r",
  "Tailors For Men\r",
  "Tailors For Uniform\r",
  "Tailors For Women\r",
  "Tailors For Women Blouse\r",
  "Tailors For Women Sharara\r",
  "Tally Training Institutes\r",
  "Tankers On Rent\r",
  "Taxi Services\r",
  "Taxi Services For Palwal\r",
  "Tea Jar Dealers\r",
  "Teacher Training Institutes\r",
  "Teak Wood Dealers\r",
  "Teak Wood Dealers-Timber\r",
  "Teak Wood Door Manufacturers\r",
  "Tempo Travellers On Rent\r",
  "Tempo Travellers On Rent For Outstation\r",
  "Tempos On Hire\r",
  "Tent Dealers\r",
  "Tent House\r",
  "Tents On Rent\r",
  "Test Tube Baby Centres\r",
  "Textile Wholesalers\r",
  "Tie Manufacturers\r",
  "Tie Wholesalers\r",
  "Tile Contractors\r",
  "Tile Dealers\r",
  "Tile Display Stand Manufacturers\r",
  "Timber Dealers\r",
  "Timber Merchants\r",
  "Tour Operators\r",
  "Tour Packages\r",
  "Tour Packages For Goa\r",
  "Tourist Attraction\r",
  "Tourist Information Centres\r",
  "Towel Manufacturers\r",
  "Tower Cranes On Rent\r",
  "Towers & Buildings\r",
  "Toy Dealers\r",
  "Toy Shops\r",
  "Track Suit Manufacturers\r",
  "Tractors On Rent\r",
  "Traditional Wears On Rent\r",
  "Trailer Body Manufacturers\r",
  "Training Centres\r",
  "Transport Agents\r",
  "Transporters\r",
  "Transporters For Ahmedabad\r",
  "Transporters For All India\r",
  "Transporters For Bangalore\r",
  "Transporters For Container\r",
  "Transporters For Pune\r",
  "Travel Agents\r",
  "Trolley Bag Manufacturers\r",
  "Truck Dealers\r",
  "Trucks On Rent\r",
  "Trucks On Rent-Tata\r",
  "Trucks On Rent-Tata 1109\r",
  "Tube Light Dealers\r",
  "Turbans On Rent\r",
  "Tutorials\r",
  "Tutorials For Class X\r",
  "Tutorials For Class XI\r",
  "Tutorials For Cma\r",
  "Tuxedo Suit On Rent\r",
  "Two Wheeler Washing Services\r",
  "Undergarment Retailers-Jockey\r",
  "Uniform Fabric Manufacturers\r",
  "Uniform Manufacturers\r",
  "Uniform Retailers\r",
  "Unisex Beauty Parlours\r",
  "Unisex Salons\r",
  "Universities\r",
  "Upholstery Retailers\r",
  "Upvc Wardrobe Dealers\r",
  "Urdu Medium Schools\r",
  "Urologist Doctors\r",
  "Utensil Dealers\r",
  "Utensil Scrubber Dealers\r",
  "Utensil Wholesalers\r",
  "Valve Dealers\r",
  "Vehicle Tracking System Dealers\r",
  "Venetian Blind Dealers\r",
  "Video Shooting Services\r",
  "Visa Assistance\r",
  "Visitor Chair Manufacturers\r",
  "Vocational Colleges\r",
  "Vocational Course Training Centres\r",
  "Volvo Bus On Rent\r",
  "Wall Clock Dealers-Ajanta\r",
  "Wall Mounted Dining Table Dealers\r",
  "Wall Painting Services\r",
  "Wall Paper Dealers\r",
  "Wardrobe Manufacturers\r",
  "Wardrobe Wholesalers\r",
  "Washing Machines On Rent\r",
  "Water Bed Dealers\r",
  "Water Bottle Dealers\r",
  "Water Bottle Dealers-Tupperware\r",
  "Water Bottle Distributors\r",
  "Water Purifier Dealers\r",
  "Waterproofing Contractors\r",
  "Wedding Bands\r",
  "Wedding Boutiques\r",
  "Wedding Decorators\r",
  "Wedding Gown Manufacturers\r",
  "Wedding Gown Retailers\r",
  "Wedding Gowns On Rent\r",
  "Wedding Photographers\r",
  "Wedding Readymade Garments On Rent\r",
  "Wedding Sarees On Rent\r",
  "Wedding Suit Retailers\r",
  "Wedding Suits On Rent\r",
  "Weight Loss Centres\r",
  "Wheel Chair Dealers\r",
  "Window Curtain Dealers\r",
  "Wireless CCTV Dealers\r",
  "Women Bag Dealers\r",
  "Women Beauty Parlours\r",
  "Women Beauty Parlours (Premium)\r",
  "Women Boutiques\r",
  "Women Hand Bag Manufacturers\r",
  "Women Home Tutors\r",
  "Women Kurti Retailers\r",
  "Women Kurti Wholesalers\r",
  "Women Readymade Garment Retailers\r",
  "Wood Dealers\r",
  "Wood Merchants\r",
  "Wooden Bed Dealers\r",
  "Wooden Bed Manufacturers\r",
  "Wooden Cabinet Dealers-Arvind Furniture\r",
  "Wooden Chair Manufacturers\r",
  "Wooden Cupboard Manufacturers\r",
  "Wooden Cupboard Wholesalers\r",
  "Wooden Door Dealers\r",
  "Wooden Door Manufacturers\r",
  "Wooden Furniture Dealers\r",
  "Wooden Furniture Dealers-Klazovyn\r",
  "Wooden Furniture Leg Manufacturers\r",
  "Wooden Furniture Manufacturers\r",
  "Wooden Handicraft Manufacturers\r",
  "Wooden Modular Kitchen Manufacturers\r",
  "Wooden Office Table Dealers\r",
  "Wooden School Furniture Dealers\r",
  "Wooden Single Bed Dealers\r",
  "Wooden Temple Manufacturers\r",
  "Wooden Temple Model Dealers\r",
  "Woollen Blanket Manufacturers\r",
  "Wrought Iron Bed Dealers\r",
  "Wrought Iron Chair Manufacturers\r",
  "Wrought Iron Double Bed Manufacturers\r",
  "Wrought Iron Furniture Dealers\r",
  "Wrought Iron Furniture Manufacturers\r",
  "Yemeni Restaurants\r",
  "Yoga Centres\r"
];
